require("moonscript")
local add, mul, div
do
  local _obj_0 = require("src/api")
  add, mul, div = _obj_0.add, _obj_0.mul, _obj_0.div
end
return context("Sample API", function()
  context("add", function()
    it("Should do addition", function()
      return assert_equal(add(40, 2), 42)
    end)
    it("Should do subtraction through addition", function()
      return assert_equal(add(44, -2), 42)
    end)
    return it("Should accept decimal numbers", function()
      return assert_equal(add(41.5, .5), 42)
    end)
  end)
  context("mul", function()
    it("Should do multiplication", function()
      return assert_equal(mul(21, 2), 42)
    end)
    it("Should do division through mulitplication", function()
      return assert_equal(mul(84, .5), 42)
    end)
    return it("Should accept decimal numbers", function()
      return assert_equal(mul(35, 1.2), 42)
    end)
  end)
  return context("div", function()
    return it("Should do division", function()
      return assert_equal(div(84, 2), 42)
    end)
  end)
end)
